# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 10000
  encoding: unicode

development:
  <<: *default
  database: blogin15_development

test:
  <<: *default
  database: blogin15_test

production:
  <<: *default
  database: blogin15_production
