# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b44cea242d3621f7f1583f069603266e1c24775dfde7e8f6bd097382495ed6d7a9fa6c239b39ab2c5d19678699c07f92dcc14c350366cf1a4495adcc397576be

test:
  secret_key_base: 55f4104c7550bbdc118229c83111891e9954ca30c14dad3e4d65d282a18f278869b7a899e130407c526d70e85086abda82ed62eb8697c89112076f5c1d221816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
