
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  timeout: 10000

development:
  <<: *default
  database: blogin14_development

test:
  <<: *default
  database: blogin14_test

production:
  <<: *default
  database: blogin14_production
